# Generated by Django 3.0.6 on 2020-05-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitodb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='api_details',
            new_name='api_detail',
        ),
    ]
